on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  simple:
    name: "Run Pytest Summary"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
			- name: "Set up Python"
        uses: actions/setup-python@main
			  with:
       	  python-version: "3.12"
      - name: "Run tests"
        uses: dariocurr/pytest-summary@v2.4
        with:
          paths: module_4/tests/**.py
          show: all

