on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  simple:
    name: "Run Pytest Summary"
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Python"
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
      - name: "Run tests"
        uses: dariocurr/pytest-summary@v2.4
        with: 
          paths: |
            module_4/tests/test_analysis_format.py
            module_4/tests/test_buttons.py
            module_4/tests/test_db_insert.py
            module_4/tests/test_flask_page.py
            module_4/tests/test_integration_end_to_end.py
          show: all

