on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  run-python-script:
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: python
          PGDATABASE:
            test_database
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.14.2"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r module_4/requirements.txt
      - name: Connect to postgres
        run: |
          sudo systemctl start postgresql.service
          psql -d postgresql://postgres@localhost/test_database -f module_4/tests/create_table.sql
      - name: "Run tests"
        run: |
          pip install pytest
          pytest module_4
